name: Worldbridger Crystalworks
favicon: null
layout_spectrum: 0.825103476177901
typography_spectrum: 0.8719816796947271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#65478f'
    - '#1c00ad'
    - '#8a8a8a'
    - '#ed971d'
  brandStrength: 0.8979333338793367
  lightness: 0.9115484191570431
  saturation: 0.9084855534601957
  rhythmicContrast: 0.8686968325637281
purpose: []
